### ISSUE TITLE
Provide a nice way to reset the state

### ISSUE THREAD

**Issue by julien-f** [JsCommunity/reaclette#2]
Useful with forms.

**Comment by julien-f** [comment]
Maybe `initialState` could be available as a local effect (not inherited).

**Comment by badrAZ** [comment]
I agree to avoid declaring a useless reset effect.

**Comment by julien-f** [comment]
After discussing with people, we agreed that this magical effect is weird, and that it would be better to provide a `store.resetState` function which would call `initialState`.
